[workspace]
members = [
    "keycodemap",
    "qemu-display",
    "qemu-rdw",
    "qemu-vnc",
    "qemu-vte",
    "xtask",
]
default-members = ["qemu-rdw"]
resolver = "2"

[workspace.dependencies]
qemu-display = { path = "qemu-display", version = "0.1" }
keycodemap = { path = "keycodemap", version = "0.1" }
zbus = "4"

[patch.crates-io]
zbus = { git = "https://github.com/dbus2/zbus.git" }
zvariant = { git = "https://github.com/dbus2/zbus.git" }
vnc = { git = "https://github.com/elmarco/rust-vnc", branch = "server" }
rdw4 = { git = "https://gitlab.gnome.org/malureau/rdw.git" }
