[workspace]
members = [
    "keycodemap",
    "qemu-display",
    "qemu-rdw",
    "qemu-vnc",
    "qemu-vte",
    "xtask",
]
default-members = ["qemu-rdw"]
resolver = "2"

[patch.crates-io]
zbus = { git = "https://github.com/dbus2/zbus.git" }
zvariant = { git = "https://github.com/dbus2/zbus.git" }
vnc = { git = "https://github.com/elmarco/rust-vnc", branch = "server" }
rdw4 = { path = "../rdw/rdw4" }
