[package]
name = "qemu-rdp"
version = "0.1.0"
authors = ["Mihnea Buzatu <mihneabuzatu88@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qemu-display = { path = "../qemu-display" }
tracing.workspace = true
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
keycodemap = { path = "../keycodemap" }
bytes = "1.6"
pixman-sys = "0.1.0"
rustls = { version = "0.21" }
rustls-pemfile = "1.0"
tokio = { version = "1.37", features = ["full"] }
tokio-rustls = "0.24"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive", "cargo"] }
async-trait = "0.1"
ironrdp = { git = "https://github.com/Devolutions/IronRDP", features = ["server", "svc", "cliprdr"] }
